//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PiChat.Bll.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PiChat.Bll.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string acc {
            get {
                return ResourceManager.GetString("acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string act {
            get {
                return ResourceManager.GetString("act", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string act1 {
            get {
                return ResourceManager.GetString("act1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string brw {
            get {
                return ResourceManager.GetString("brw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string can {
            get {
                return ResourceManager.GetString("can", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Description.
        /// </summary>
        public static string cdes {
            get {
                return ResourceManager.GetString("cdes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change group description.
        /// </summary>
        public static string cgd {
            get {
                return ResourceManager.GetString("cgd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change group name.
        /// </summary>
        public static string cgn {
            get {
                return ResourceManager.GetString("cgn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change image description.
        /// </summary>
        public static string cid {
            get {
                return ResourceManager.GetString("cid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string cl {
            get {
                return ResourceManager.GetString("cl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Name.
        /// </summary>
        public static string cname {
            get {
                return ResourceManager.GetString("cname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new group.
        /// </summary>
        public static string cng {
            get {
                return ResourceManager.GetString("cng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string cpass {
            get {
                return ResourceManager.GetString("cpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change picture.
        /// </summary>
        public static string cpic {
            get {
                return ResourceManager.GetString("cpic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string cr {
            get {
                return ResourceManager.GetString("cr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your name.
        /// </summary>
        public static string cyn {
            get {
                return ResourceManager.GetString("cyn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        public static string cyp {
            get {
                return ResourceManager.GetString("cyp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string del {
            get {
                return ResourceManager.GetString("del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string desc {
            get {
                return ResourceManager.GetString("desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string err {
            get {
                return ResourceManager.GetString("err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Error.
        /// </summary>
        public static string err1 {
            get {
                return ResourceManager.GetString("err1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Error.
        /// </summary>
        public static string err2 {
            get {
                return ResourceManager.GetString("err2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept request error.
        /// </summary>
        public static string err3 {
            get {
                return ResourceManager.GetString("err3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject request error.
        /// </summary>
        public static string err4 {
            get {
                return ResourceManager.GetString("err4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group delete error.
        /// </summary>
        public static string err5 {
            get {
                return ResourceManager.GetString("err5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server error.
        /// </summary>
        public static string err6 {
            get {
                return ResourceManager.GetString("err6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image delete error.
        /// </summary>
        public static string err7 {
            get {
                return ResourceManager.GetString("err7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin grant failed.
        /// </summary>
        public static string err8 {
            get {
                return ResourceManager.GetString("err8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the operation couldn&apos;t be executed..
        /// </summary>
        public static string errX {
            get {
                return ResourceManager.GetString("errX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please refresh the page or try again later..
        /// </summary>
        public static string errY {
            get {
                return ResourceManager.GetString("errY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You either don&apos;t have authority or there is a problem with the server, refresh page and try again.
        /// </summary>
        public static string errZ {
            get {
                return ResourceManager.GetString("errZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Error.
        /// </summary>
        public static string ferr1 {
            get {
                return ResourceManager.GetString("ferr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select files (less than 100MB), or try again later.
        /// </summary>
        public static string ferr2 {
            get {
                return ResourceManager.GetString("ferr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string fil {
            get {
                return ResourceManager.GetString("fil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files:.
        /// </summary>
        public static string fl {
            get {
                return ResourceManager.GetString("fl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string fresh {
            get {
                return ResourceManager.GetString("fresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Group Selected.
        /// </summary>
        public static string gerr1 {
            get {
                return ResourceManager.GetString("gerr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an existing group.
        /// </summary>
        public static string gerr2 {
            get {
                return ResourceManager.GetString("gerr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong group.
        /// </summary>
        public static string gerr3 {
            get {
                return ResourceManager.GetString("gerr3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string gr {
            get {
                return ResourceManager.GetString("gr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string grp {
            get {
                return ResourceManager.GetString("grp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        public static string grpnm {
            get {
                return ResourceManager.GetString("grpnm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string hom {
            get {
                return ResourceManager.GetString("hom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size.
        /// </summary>
        public static string imgs {
            get {
                return ResourceManager.GetString("imgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Requests.
        /// </summary>
        public static string jreq {
            get {
                return ResourceManager.GetString("jreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        public static string lg {
            get {
                return ResourceManager.GetString("lg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string log {
            get {
                return ResourceManager.GetString("log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you don&apos;t have an account, click here to register..
        /// </summary>
        public static string logmsg {
            get {
                return ResourceManager.GetString("logmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string md {
            get {
                return ResourceManager.GetString("md", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string mem {
            get {
                return ResourceManager.GetString("mem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show More.
        /// </summary>
        public static string more {
            get {
                return ResourceManager.GetString("more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no groups or subscribes..
        /// </summary>
        public static string msg1 {
            get {
                return ResourceManager.GetString("msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password could not be changed.
        /// </summary>
        public static string msg10 {
            get {
                return ResourceManager.GetString("msg10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name could not be changed.
        /// </summary>
        public static string msg11 {
            get {
                return ResourceManager.GetString("msg11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the end of the line, ain&apos;t no more groups..
        /// </summary>
        public static string msg2 {
            get {
                return ResourceManager.GetString("msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no groups for the requested filter..
        /// </summary>
        public static string msg3 {
            get {
                return ResourceManager.GetString("msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There isn&apos;t a group where you didn&apos;t subscribe to..
        /// </summary>
        public static string msg4 {
            get {
                return ResourceManager.GetString("msg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the end of the line, ain&apos;t no more images..
        /// </summary>
        public static string msg5 {
            get {
                return ResourceManager.GetString("msg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No images in the group..
        /// </summary>
        public static string msg6 {
            get {
                return ResourceManager.GetString("msg6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Image description could not be changed..
        /// </summary>
        public static string msg7 {
            get {
                return ResourceManager.GetString("msg7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name couldn&apos;t be changed.
        /// </summary>
        public static string msg8 {
            get {
                return ResourceManager.GetString("msg8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The group couldn&apos;t be created.
        /// </summary>
        public static string msg9 {
            get {
                return ResourceManager.GetString("msg9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My groups.
        /// </summary>
        public static string myg {
            get {
                return ResourceManager.GetString("myg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New description.
        /// </summary>
        public static string nd {
            get {
                return ResourceManager.GetString("nd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name.
        /// </summary>
        public static string nn {
            get {
                return ResourceManager.GetString("nn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string npass {
            get {
                return ResourceManager.GetString("npass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password confirm.
        /// </summary>
        public static string npconf {
            get {
                return ResourceManager.GetString("npconf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owned and Administrated Groups.
        /// </summary>
        public static string ogrp {
            get {
                return ResourceManager.GetString("ogrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it!.
        /// </summary>
        public static string ok1 {
            get {
                return ResourceManager.GetString("ok1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string opass {
            get {
                return ResourceManager.GetString("opass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other groups.
        /// </summary>
        public static string oth {
            get {
                return ResourceManager.GetString("oth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Name.
        /// </summary>
        public static string owrnm {
            get {
                return ResourceManager.GetString("owrnm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string pass {
            get {
                return ResourceManager.GetString("pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending....
        /// </summary>
        public static string pen {
            get {
                return ResourceManager.GetString("pen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        public static string pic {
            get {
                return ResourceManager.GetString("pic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string pic1 {
            get {
                return ResourceManager.GetString("pic1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A popup dialog could not open, refresh the page.
        /// </summary>
        public static string pop1 {
            get {
                return ResourceManager.GetString("pop1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup error.
        /// </summary>
        public static string pop2 {
            get {
                return ResourceManager.GetString("pop2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string priv {
            get {
                return ResourceManager.GetString("priv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string prof {
            get {
                return ResourceManager.GetString("prof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile page.
        /// </summary>
        public static string profp {
            get {
                return ResourceManager.GetString("profp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string prog {
            get {
                return ResourceManager.GetString("prog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promote.
        /// </summary>
        public static string prom {
            get {
                return ResourceManager.GetString("prom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string que1 {
            get {
                return ResourceManager.GetString("que1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This image will be deleted permanently..
        /// </summary>
        public static string que2 {
            get {
                return ResourceManager.GetString("que2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Image.
        /// </summary>
        public static string que3 {
            get {
                return ResourceManager.GetString("que3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string que4 {
            get {
                return ResourceManager.GetString("que4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string que5 {
            get {
                return ResourceManager.GetString("que5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This group and all of it&apos;s images will be deleted permanently..
        /// </summary>
        public static string que6 {
            get {
                return ResourceManager.GetString("que6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete group.
        /// </summary>
        public static string que7 {
            get {
                return ResourceManager.GetString("que7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string reg {
            get {
                return ResourceManager.GetString("reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is in use.
        /// </summary>
        public static string regerr1 {
            get {
                return ResourceManager.GetString("regerr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong email adress.
        /// </summary>
        public static string regerr2 {
            get {
                return ResourceManager.GetString("regerr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you already have an account, click here to login..
        /// </summary>
        public static string regmsg {
            get {
                return ResourceManager.GetString("regmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string rej {
            get {
                return ResourceManager.GetString("rej", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string rem {
            get {
                return ResourceManager.GetString("rem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string ren {
            get {
                return ResourceManager.GetString("ren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required..
        /// </summary>
        public static string req {
            get {
                return ResourceManager.GetString("req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string sav {
            get {
                return ResourceManager.GetString("sav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select and upload new pictures.
        /// </summary>
        public static string sel {
            get {
                return ResourceManager.GetString("sel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        public static string sm {
            get {
                return ResourceManager.GetString("sm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string stat {
            get {
                return ResourceManager.GetString("stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string sub {
            get {
                return ResourceManager.GetString("sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string suc1 {
            get {
                return ResourceManager.GetString("suc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your files uploaded successfully.
        /// </summary>
        public static string suc2 {
            get {
                return ResourceManager.GetString("suc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string sz {
            get {
                return ResourceManager.GetString("sz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is required..
        /// </summary>
        public static string treq {
            get {
                return ResourceManager.GetString("treq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe.
        /// </summary>
        public static string uns {
            get {
                return ResourceManager.GetString("uns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string upl {
            get {
                return ResourceManager.GetString("upl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag files here to upload.
        /// </summary>
        public static string upl1 {
            get {
                return ResourceManager.GetString("upl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload images.
        /// </summary>
        public static string upli {
            get {
                return ResourceManager.GetString("upli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email must be a valid email address..
        /// </summary>
        public static string val1 {
            get {
                return ResourceManager.GetString("val1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad username or password..
        /// </summary>
        public static string val2 {
            get {
                return ResourceManager.GetString("val2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password has to be less than 32 characters long..
        /// </summary>
        public static string val3 {
            get {
                return ResourceManager.GetString("val3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password has to be more than 5 characters long..
        /// </summary>
        public static string val4 {
            get {
                return ResourceManager.GetString("val4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain at least 1 small, 1 capital letter, 1 number..
        /// </summary>
        public static string val5 {
            get {
                return ResourceManager.GetString("val5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string val6 {
            get {
                return ResourceManager.GetString("val6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which group will you upload to?.
        /// </summary>
        public static string wgwyut {
            get {
                return ResourceManager.GetString("wgwyut", resourceCulture);
            }
        }
    }
}
